export const quotes = [
    "Sometimes it takes a long time to sound like yourself. - Miles Davis",
            "It’s simple... just keep going, keep going, keep going, and one day it will be your turn. And when that happens, you just have to take full advantage of your turn - Young Thug",
            "I take great care of myself by carefully shutting myself away. - Vincent Van Gogh",
            "Perfection is the absence of human sensibility.",
            "Artistic expression is the only way to recontextualize & re-package the experiences that we endure.",
            "It’s very possible to design things that make people happier to be alive.",
            "Operating in authenticity eliminates the need for outside validation.",
            "Sacrifice gives better context to achievement.",
            "Discomfort is the greatest source for creation - innovation is bred from necessity.",
            "Nobody will see your work the same way you do - that’s a beautiful thing.",
            "You’re here for a reason.",
            "A wise old owl sat on an oak. The more he saw, the less he spoke. The less he spoke, the more he heard. Now wasn’t that a wise old bird? - English nursery rhyme",
            "Sometimes it’s impossible to justify the creative outcome with language and rules. If it feels right, it is right. No explanation needed.",
            "Work or rest, but never wait.",
            "It’s a gift and a responsibility to be inspired enough to take action through creation.",
            "Creating things is cool, but real life matters most.",
            "Sketches are often more interesting than the final product.",
            "Never hold things too precious - wear & tear = signs of [unique] life.",
            "I know I’m in the right place when I have no idea what’s going to happen next.",
            "I’ve never been more excited to be alive than when I’m chasing my dreams.",
            "Luxury is a feeling.",
            "Less words carry more weight.",
            "Nothing is absolute.",
            "Don’t think too much - your art gets diluted the more you try to rationalize the emotions. The world needs your unfiltered expression.",
            "Sometimes, the process is the artwork itself.",
            "Talk is empty. Go get it.",
];